#!/usr/bin/env swift
// Renders Resources/AppIcon.icns from code so the repo carries no binary asset that has to
// be regenerated by hand. Run: swift Scripts/make_icon.swift
import AppKit

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
let iconset = root.appendingPathComponent("build/AppIcon.iconset")
try? FileManager.default.createDirectory(at: iconset, withIntermediateDirectories: true)

func drawIcon(side: CGFloat) -> NSImage {
    let image = NSImage(size: NSSize(width: side, height: side))
    image.lockFocus()
    defer { image.unlockFocus() }
    guard let context = NSGraphicsContext.current?.cgContext else { return image }

    // macOS app icons sit inside a squircle with a little breathing room.
    let inset = side * 0.055
    let rect = CGRect(x: inset, y: inset, width: side - inset * 2, height: side - inset * 2)
    let squircle = NSBezierPath(roundedRect: rect, xRadius: side * 0.225, yRadius: side * 0.225)

    context.saveGState()
    squircle.addClip()
    let gradient = NSGradient(colors: [
        NSColor(calibratedRed: 0.29, green: 0.44, blue: 0.98, alpha: 1),
        NSColor(calibratedRed: 0.44, green: 0.25, blue: 0.86, alpha: 1)
    ])
    gradient?.draw(in: rect, angle: -90)
    context.restoreGState()

    // A mouse outline with a vertical arrow through the wheel: scrolling, reversible.
    let config = NSImage.SymbolConfiguration(pointSize: side * 0.5, weight: .medium)
    if let glyph = NSImage(systemSymbolName: "computermouse.fill", accessibilityDescription: nil)?
        .withSymbolConfiguration(config) {
        let tinted = NSImage(size: glyph.size)
        tinted.lockFocus()
        NSColor.white.set()
        NSRect(origin: .zero, size: glyph.size).fill(using: .sourceOver)
        glyph.draw(at: .zero, from: .zero, operation: .destinationIn, fraction: 1)
        tinted.unlockFocus()

        let target = CGRect(
            x: (side - glyph.size.width) / 2,
            y: (side - glyph.size.height) / 2,
            width: glyph.size.width,
            height: glyph.size.height
        )
        tinted.draw(in: target, from: .zero, operation: .sourceOver, fraction: 0.95)
    }
    return image
}

// The sizes `iconutil` expects, each in 1x and 2x form.
for base in [16, 32, 128, 256, 512] {
    for scale in [1, 2] {
        let side = CGFloat(base * scale)
        let image = drawIcon(side: side)
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:])
        else { continue }
        let suffix = scale == 1 ? "" : "@2x"
        let name = "icon_\(base)x\(base)\(suffix).png"
        try png.write(to: iconset.appendingPathComponent(name))
    }
}

let convert = Process()
convert.executableURL = URL(fileURLWithPath: "/usr/bin/iconutil")
convert.arguments = [
    "-c", "icns", iconset.path,
    "-o", root.appendingPathComponent("Resources/AppIcon.icns").path
]
try convert.run()
convert.waitUntilExit()
print(convert.terminationStatus == 0 ? "wrote Resources/AppIcon.icns" : "iconutil failed")
